
Creating datasets
Traceback (most recent call last):
  File "D:\ResearchProject\Artwork-Interpretation\KALE.py", line 373, in <module>
    main(args, config)
  File "D:\ResearchProject\Artwork-Interpretation\KALE.py", line 196, in main
    datasets = create_dataset('semart_contextual', config)
  File "D:\ResearchProject\Artwork-Interpretation\dataset\__init__.py", line 76, in create_dataset
    train_dataset = sa_dataset(['/data/gpfs/projects/punim1996/Data/SemArt/processed_semart_train.json'], train_transform, '/data/gpfs/projects/punim1996/Data/SemArt/Images',
  File "D:\ResearchProject\Artwork-Interpretation\dataset\caption_dataset.py", line 33, in __init__
    self.ann += json.load(open(f, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/data/gpfs/projects/punim1996/Data/SemArt/processed_semart_train.json'